uploads = []
outputs = []

[[generated]]
id = "ZCXWMuVmS3hfoY_l-PdXN"
uri = "file://artifacts/cocoon-wellness/public/images/hero.png"
type = "image"
title = "Hero image for wellness sanctuary"

[[generated]]
id = "fpBOmjDAo7tNNd7wqQAAO"
uri = "file://artifacts/cocoon-wellness/public/images/hair-studio.png"
type = "image"
title = "Hair studio"

[[generated]]
id = "cYH5OrmMiTK_xYiwktacV"
uri = "file://artifacts/cocoon-wellness/public/images/service-women.png"
type = "image"
title = "Womens world spa"

[[generated]]
id = "IHo8yz8mFJl4dHvIMNFNU"
uri = "file://artifacts/cocoon-wellness/public/images/service-men.png"
type = "image"
title = "Mens world spa"

[[generated]]
id = "QSXGacbErnb7IUEj-VPS3"
uri = "file://artifacts/cocoon-wellness/public/images/service-kids.png"
type = "image"
title = "Childrens world spa"

[[generated]]
id = "IgsMnnFi1_do0uMOg0mDC"
uri = "file://artifacts/cocoon-wellness/public/images/service-pets.png"
type = "image"
title = "Pets world spa"

[[generated]]
id = "UzMUvXO-_9Vi7ejHud-vM"
uri = "file://artifacts/cocoon-wellness/public/images/philosophy.png"
type = "image"
title = "Philosophy image"

[[generated]]
id = "vu0e5uZtevFAVaQzhvb8U"
uri = "file://artifacts/cocoon-wellness/public/images/sanctuary.png"
type = "image"
title = "Sanctuary spaces"

[[generated]]
id = "nNvfIynqw7xiq-QksnGp8"
uri = "file://artifacts/cocoon-wellness/public/images/stay-standard.png"
type = "image"
title = "Stay package standard"

[[generated]]
id = "vUvofj1FTmeUscTDJNWO8"
uri = "file://artifacts/cocoon-wellness/public/images/stay-vip.png"
type = "image"
title = "Stay package VIP"
